import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders


def send_meeting_report_email(to_email: str, pdf_path: str, meeting_title: str = "Meeting Report") -> dict:
    """
    Sends the meeting report PDF as an attachment to whatever email address
    is passed in. Uses Gmail SMTP with an app password (works headlessly,
    no browser-based OAuth consent needed - required for cloud deployment).

    Requires two environment variables (set as Streamlit secrets in deployment):
      GMAIL_ADDRESS       - the Gmail account sending the report
      GMAIL_APP_PASSWORD  - a 16-character app password (NOT your normal
                             Gmail password). Generate one at
                             https://myaccount.google.com/apppasswords
                             (requires 2-Step Verification to be enabled).
    """
    sender_email = os.getenv("GMAIL_ADDRESS")
    app_password = os.getenv("GMAIL_APP_PASSWORD")

    if not sender_email or not app_password:
        return {
            "success": False,
            "error": "Email sending is not configured. Set GMAIL_ADDRESS and "
                     "GMAIL_APP_PASSWORD environment variables."
        }

    try:
        message = MIMEMultipart()
        message["From"] = sender_email
        message["To"] = to_email
        message["Subject"] = f"Meeting Report: {meeting_title}"

        body_text = """Hi,

Please find attached the meeting report, including summary, key decisions, and action items.

This was automatically generated by the Meeting Assistant.
"""
        message.attach(MIMEText(body_text))

        with open(pdf_path, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f"attachment; filename={os.path.basename(pdf_path)}"
        )
        message.attach(part)

        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(sender_email, app_password)
            server.sendmail(sender_email, to_email, message.as_string())

        return {"success": True, "error": None}

    except Exception as e:
        return {"success": False, "error": str(e)}