import os
import base64
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

SCOPES = ["https://www.googleapis.com/auth/gmail.send"]


def get_gmail_service():
    creds = None
    if os.path.exists("token.json"):
        creds = Credentials.from_authorized_user_file("token.json", SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file("credentials.json", SCOPES)
            creds = flow.run_local_server(port=0)
        with open("token.json", "w") as token:
            token.write(creds.to_json())
    return build("gmail", "v1", credentials=creds)


def send_meeting_report_email(to_email: str, pdf_path: str, meeting_title: str = "Meeting Report") -> dict:
    """
    Sends the CEO an email with the meeting report PDF attached.
    """
    try:
        service = get_gmail_service()

        message = MIMEMultipart()
        message["to"] = to_email
        message["subject"] = f"Meeting Report: {meeting_title}"

        body_text = f"""Hi,

Please find attached the meeting report, including summary, key decisions, and action items.

This was automatically generated by the Meeting Assistant.
"""
        message.attach(MIMEText(body_text))

        with open(pdf_path, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f"attachment; filename={os.path.basename(pdf_path)}"
        )
        message.attach(part)

        raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode()
        service.users().messages().send(userId="me", body={"raw": raw_message}).execute()

        return {"success": True, "error": None}

    except Exception as e:
        return {"success": False, "error": str(e)}